# -*- coding: utf-8 -*-
"""dashboard_gunung

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RujkFiHm0S20d5-VfyU4EzOmyWdmzt-n
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.metrics.pairwise import cosine_similarity
from tensorflow.keras.models import load_model

# ===============================
# LOAD MODEL & DATA
# ===============================
df = pd.read_csv("dataset_gunung_preprocessed.csv")

scaler = joblib.load("scaler.pkl")
le_diff = joblib.load("le_diff.pkl")
le_level = joblib.load("le_level.pkl")
mlp_model = load_model("mlp_model_gunung.keras")

features = ['elevation_scaled','duration_scaled','distance_scaled','gain_scaled',
            'difficulty_encoded','level_encoded']

# ===============================
# CBF FUNCTION
# ===============================
def cbf_score(df, user_vector):
    sim = cosine_similarity(user_vector, df[features])
    return sim[0]

def content_based_recommendation(user_input, df, top_n=5):
    scaled = scaler.transform([[user_input['elevation_m'],
                                user_input['hiking_duration_hours'],
                                user_input['distance_km'],
                                user_input['Elevation_gain']]])[0]

    user_vector = np.array([[scaled[0], scaled[1], scaled[2], scaled[3],
                             le_diff.transform([user_input['difficulty_level']])[0],
                             le_level.transform([user_input['recommended_for']])[0]]])

    df_copy = df.copy()
    df_copy['similarity'] = cbf_score(df_copy, user_vector)

    return df_copy.sort_values('similarity', ascending=False).head(top_n)

# ===============================
# STREAMLIT UI STYLE
# ===============================
st.set_page_config(page_title="Mount Jawa", layout="wide")

# Custom CSS for clean UI
st.markdown("""
    <style>
        body {
            background-color: #f8f9fa;
        }
        .big-title {
            font-size: 48px;
            font-weight: 800;
            text-align: center;
            color: white;
            margin-top: 150px;
            text-shadow: 2px 2px 8px rgba(0,0,0,0.6);
        }
        .sub-title {
            font-size: 22px;
            text-align: center;
            color: white;
            margin-bottom: 250px;
            text-shadow: 2px 2px 6px rgba(0,0,0,0.5);
        }
        .recommend-title {
            font-size: 32px;
            font-weight: 700;
            margin-bottom: 20px;
        }
        .card {
            background: white;
            padding: 20px;
            border-radius: 18px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.08);
            margin-bottom: 25px;
        }
        .gunung-image {
            width: 100%;
            height: 280px;
            border-radius: 14px;
            object-fit: cover;
            margin-bottom: 15px;
        }
    </style>
""", unsafe_allow_html=True)

# ===============================
# LANDING PAGE
# ===============================
with st.container():
    st.markdown("""
        <div style="
            background-image: url('https://images.unsplash.com/photo-1501785888041-af3ef285b470');
            background-size: cover;
            background-position: center;
            height: 500px;
            width: 100%;
            border-radius: 18px;
            margin-bottom: 40px;">
            <h1 class="big-title">Welcome to Mount Jawa</h1>
            <p class="sub-title">Temukan rekomendasi gunung terbaik sesuai preferensimu</p>
        </div>
    """, unsafe_allow_html=True)

# ===============================
# USER INPUT
# ===============================
st.sidebar.header("🧭 Input Pendaki")

elev = st.sidebar.number_input("Elevasi yang diinginkan (meter)", 0, 4000, 2000)
dur = st.sidebar.number_input("Durasi pendakian (jam)", 1, 40, 10)
dist = st.sidebar.number_input("Jarak pendakian (km)", 1, 50, 10)
gain = st.sidebar.number_input("Elevation Gain (m)", 0, 3000, 800)

diff = st.sidebar.selectbox("Tingkat Kesulitan", le_diff.classes_)
recom = st.sidebar.selectbox("Direkomendasikan Untuk", le_level.classes_)

submit = st.sidebar.button("Tampilkan Rekomendasi")

# ===============================
# RECOMMENDATION RESULT
# ===============================
if submit:
    user_input = {
        'elevation_m': elev,
        'hiking_duration_hours': dur,
        'distance_km': dist,
        'Elevation_gain': gain,
        'difficulty_level': diff,
        'recommended_for': recom
    }

    cbf_result = content_based_recommendation(user_input, df, top_n=5)

    # MLP score
    X_candidate = cbf_result[features].values
    cbf_result['mlp_score'] = mlp_model.predict(X_candidate).flatten()

    # Final ranking
    cbf_result['final_score'] = (
        cbf_result['similarity'] * 0.6 +
        cbf_result['mlp_score'] * 0.4
    )

    final_result = cbf_result.sort_values("final_score", ascending=False)

    st.markdown('<h2 class="recommend-title">✨ Rekomendasi Gunung untuk Kamu</h2>', unsafe_allow_html=True)

    for idx, row in final_result.iterrows():
        with st.container():
            st.markdown('<div class="card">', unsafe_allow_html=True)

            # Left: Image, Right: Info
            col1, col2 = st.columns([1.2, 2])

            with col1:
                img = row['image_url'] if isinstance(row['image_url'], str) else \
                    "https://images.unsplash.com/photo-1500534623283-312aade485b7"
                st.image(img, use_column_width=True)

            with col2:
                st.subheader(row["name"])
                st.write(f"**Elevasi:** {row['elevation_m']} m")
                st.write(f"**Durasi:** {row['hiking_duration_hours']} jam")
                st.write(f"**Jarak:** {row['distance_km']} km")
                st.write(f"**Elevation Gain:** {row['Elevation_gain']} m")
                st.write(f"**Kesulitan:** {row['difficulty_level']}")

            st.markdown('</div>', unsafe_allow_html=True)
