# -*- coding: utf-8 -*-
"""dashboard_gunung

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RujkFiHm0S20d5-VfyU4EzOmyWdmzt-n
"""

def recommend(user_input, top_n=5, alpha=0.5, beta=0.5):
    """
    user_input: dict
        {
            'Province': 'Jawa Barat',
            'difficulty_level': 'Moderate',
            'hiking_duration_hours': 5
        }
    """
    # Load file yang sudah disimpan
    scaler = pickle.load(open("scaler.pkl", "rb"))
    encoder = pickle.load(open("encoder.pkl", "rb"))
    features = np.load("features.npy")
    df = pd.read_pickle("df.pkl")

    from tensorflow.keras.models import load_model
    mlp_model = load_model("mlp_model.h5")

    # Filter dataset
    filtered = df[
        (df['Province']==user_input['Province']) &
        (df['difficulty_level']==user_input['difficulty_level'])
    ].copy()
    if filtered.empty:
        return "Tidak ada gunung sesuai kriteria."

    idx_filtered = filtered.index

    # Buat vektor user
    user_num = np.array([[0, user_input['hiking_duration_hours'], 0]])  # padding elevation & distance
    user_num_scaled = scaler.transform(user_num)
    user_cat_list = [[user_input['difficulty_level'], 'Intermediate', user_input['Province']]]
    user_cat_encoded = encoder.transform(user_cat_list).toarray()
    user_vector = np.hstack([user_num_scaled, user_cat_encoded])

    # CBF similarity
    sim_scores = cosine_similarity(user_vector, features[idx_filtered])[0]
    filtered['cbf_similarity'] = sim_scores

    # MLP scoring
    X_mlp = features[idx_filtered]
    mlp_scores = mlp_model.predict(X_mlp, verbose=0).flatten()

    # Gabungkan skor
    filtered['final_score'] = alpha * filtered['cbf_similarity'] + beta * mlp_scores
    return filtered.sort_values(by='final_score', ascending=False).head(top_n)