# -*- coding: utf-8 -*-
"""dashboard_gunung

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RujkFiHm0S20d5-VfyU4EzOmyWdmzt-n
"""


# -*- coding: utf-8 -*-
"""
Dashboard Streamlit Sistem Rekomendasi Gunung
Terhubung dengan modeling_gunung.py
"""

import streamlit as st
import pandas as pd
import numpy as np
from modeling_gunung import recommend  # pastikan file modeling_gunung.py sudah diupload
from PIL import Image
import pydeck as pdk

# ===============================
# Judul Dashboard
# ===============================
st.set_page_config(page_title="Rekomendasi Gunung Jawa", layout="wide")
st.title("🏔️ Sistem Rekomendasi Gunung di Pulau Jawa (CBF + MLP Ranking)")

# ===============================
# Background (opsional)
# ===============================
image_path = "background_gunung.jpeg"
try:
    st.image(image_path, use_container_width=True)
except:
    st.warning("Gambar background tidak ditemukan. Lanjutkan tanpa background.")

# ===============================
# Load dataset untuk input options
# ===============================
try:
    df = pd.read_pickle("df.pkl")
except FileNotFoundError:
    st.error("File df.pkl tidak ditemukan. Pastikan file sudah diupload.")
    st.stop()

province_options = df['Province'].unique()
difficulty_options = df['difficulty_level'].unique()

# ===============================
# Sidebar Input Pengguna
# ===============================
st.sidebar.header("Pilih Preferensi Pendakian")
province = st.sidebar.selectbox("Provinsi:", options=province_options)
difficulty = st.sidebar.selectbox("Tingkat Kesulitan:", options=difficulty_options)
duration = st.sidebar.slider("Durasi Pendakian (jam):", 0, 12, 4)
top_n = st.sidebar.slider("Jumlah Rekomendasi:", 1, 10, 5)

# ===============================
# Tombol Submit
# ===============================
if st.sidebar.button("Tampilkan Rekomendasi"):
    user_pref = {
        'Province': province,
        'difficulty_level': difficulty,
        'hiking_duration_hours': duration
    }

    recommendations = recommend(user_pref, top_n=top_n)

    if isinstance(recommendations, str):
        st.warning(recommendations)
    else:
        st.subheader(f"Top {top_n} Gunung Rekomendasi")
        for idx, row in recommendations.iterrows():
            st.markdown("---")
            st.subheader(row['Name'])
            st.write(f"Provinsi: {row['Province']}")
            st.write(f"Difficulty: {row['difficulty_level']}")
            st.write(f"Hiking Duration: {row['hiking_duration_hours']} jam")

            # Jika ada kolom image_url
            if 'image_url' in row and pd.notna(row['image_url']):
                st.image(row['image_url'], width=250)

            # Tombol Google Maps
            if 'Latitude' in row and 'Longitude' in row:
                maps_url = f"https://www.google.com/maps/search/?api=1&query={row['Latitude']},{row['Longitude']}"
                st.markdown(f"[Buka di Google Maps]({maps_url})")

        # ===============================
        # Peta interaktif dengan Pydeck
        # ===============================
        if 'Latitude' in recommendations and 'Longitude' in recommendations:
            layer = pdk.Layer(
                "ScatterplotLayer",
                data=recommendations,
                get_position='[Longitude, Latitude]',
                get_color='[200, 30, 0, 160]',
                get_radius=5000,
                pickable=True
            )
            view_state = pdk.ViewState(
                latitude=recommendations['Latitude'].mean(),
                longitude=recommendations['Longitude'].mean(),
                zoom=6,
                pitch=0
            )
            deck = pdk.Deck(
                map_style='mapbox://styles/mapbox/streets-v11',
                initial_view_state=view_state,
                layers=[layer],
                tooltip={
                    "text": "{Name}\nProvinsi: {Province}\nDifficulty: {difficulty_level}\nDuration: {hiking_duration_hours} jam"
                }
            )
            st.subheader("Lokasi Gunung Rekomendasi di Peta")
            st.pydeck_chart(deck)
