# -*- coding: utf-8 -*-
"""dashboard_gunung

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RujkFiHm0S20d5-VfyU4EzOmyWdmzt-n
"""

# -*- coding: utf-8 -*-
"""dashboard_gunung_no_level"""


# ===============================
# 1️⃣ Import Library
# ===============================
import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.metrics.pairwise import cosine_similarity
from tensorflow.keras.models import load_model
import pydeck as pdk
import webbrowser

# ===============================
# 2️⃣ Load Dataset & Models
# ===============================
df = pd.read_csv("dataset_gunung_preprocessed.csv")

le_diff = joblib.load("le_diff.pkl")
scaler = joblib.load("scaler.pkl")
mlp_model = load_model("mlp_model_gunung.h5", compile=False)

# ===============================
# 3️⃣ Homepage Cantik
# ===============================
st.title("🏔️ Sistem Rekomendasi Gunung Pulau Jawa")
st.markdown("""
Selamat datang di aplikasi rekomendasi pendakian gunung.
Masukkan preferensimu di sidebar, lalu sistem akan menampilkan rekomendasi gunung terbaik untukmu ✨
""")

# st.image("header.jpg", use_column_width=True)

st.sidebar.header("Preferensi Pendakian")

# ===============================
# Sidebar Input
# ===============================
province = st.sidebar.selectbox("Provinsi:", options=df['Province'].unique())
difficulty = st.sidebar.selectbox("Tingkat Kesulitan:", options=df['difficulty_level'].unique())
duration = st.sidebar.slider("Durasi Pendakian (jam):", 0, 12, 4)
max_distance = st.sidebar.slider("Jarak Maksimal (km):", 0, 50, 10)

# ===============================
# 4️⃣ CBF Function Tanpa Level
# ===============================
def content_based_recommendation(user_input, df, top_n=20):

    user_scaled = scaler.transform([[user_input['elevation_m'],
                                     user_input['hiking_duration_hours'],
                                     user_input['distance_km'],
                                     user_input['Elevation_gain']]])[0]

    user_vector = np.array([[
        user_scaled[0],
        user_scaled[1],
        user_scaled[2],
        user_scaled[3],
        le_diff.transform([user_input['difficulty_level']])[0],
    ]])

    features = [
        'elevation_scaled','duration_scaled',
        'distance_scaled','gain_scaled','difficulty_encoded'
    ]

    similarity = cosine_similarity(user_vector, df[features])
    df_result = df.copy()
    df_result['similarity'] = similarity[0]

    return df_result.sort_values('similarity', ascending=False).head(top_n)

# ===============================
# 5️⃣ User Input Dict
# ===============================
user_input = {
    'elevation_m': df[df['Province']==province]['elevation_m'].median(),
    'hiking_duration_hours': duration,
    'distance_km': max_distance,
    'Elevation_gain': df[df['Province']==province]['Elevation_gain'].median(),
    'difficulty_level': difficulty
}

# ===============================
# 6️⃣ Hitung Kandidat CBF
# ===============================
candidate_gunung = content_based_recommendation(user_input, df, top_n=20)

# ===============================
# 7️⃣ MLP Ranking
# ===============================
features = [
    'elevation_scaled','duration_scaled',
    'distance_scaled','gain_scaled','difficulty_encoded'
]

candidate_gunung['mlp_score'] = mlp_model.predict(candidate_gunung[features]).flatten()
top_gunung = candidate_gunung.sort_values('mlp_score', ascending=False).head(5)

# ===============================
# 8️⃣ Tampilkan Rekomendasi
# ===============================
st.subheader("🔥 Rekomendasi Gunung Terbaik Untukmu")

for idx, row in top_gunung.iterrows():
    st.markdown(f"### 🏔️ {row['Name']}")
    st.write(f"**Provinsi:** {row['Province']}")
    st.write(f"**Elevation:** {row['elevation_m']} m")
    st.write(f"**Kesulitan:** {row['difficulty_level']}")
    st.write(f"**Durasi:** {row['hiking_duration_hours']} jam")
    st.image(row['image_url'], width=300)

    maps_url = f"https://www.google.com/maps/search/?api=1&query={row['Latitude']},{row['Longitude']}"
    if st.button(f"Buka {row['Name']} di Google Maps", key=idx):
        webbrowser.open_new_tab(maps_url)

# ===============================
# 9️⃣ Pydeck Map
# ===============================
st.subheader("🗺️ Lokasi Gunung di Peta")

layer = pdk.Layer(
    "ScatterplotLayer",
    data=top_gunung,
    get_position='[Longitude, Latitude]',
    get_radius=5000,
    get_color='[200, 30, 0, 160]',
    pickable=True
)

view_state = pdk.ViewState(
    latitude=top_gunung['Latitude'].mean(),
    longitude=top_gunung['Longitude'].mean(),
    zoom=6
)

st.pydeck_chart(
    pdk.Deck(
        layers=[layer],
        initial_view_state=view_state,
    )
)
