# -*- coding: utf-8 -*-
"""modeling_gunung

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgRx6qhRsJfC9L7rPCE1UKcTGGFW6Unk
"""

# -*- coding: utf-8 -*-
"""
modeling_gunung.py
Full pipeline: preprocessing, CBF similarity, MLP training, simpan model/scaler/encoder/features, fungsi recommend()
"""

import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense

# === 1. Load dataset ===
df = pd.read_csv("dataset_gunung_fix.csv")

# === 2. Preprocessing Numerik & Kategorikal ===
num_features = ['elevation_m', 'hiking_duration_hours', 'distance_km']
cat_features = ['difficulty_level', 'recommended_for', 'Province']

scaler = MinMaxScaler()
num_scaled = scaler.fit_transform(df[num_features])

encoder = OneHotEncoder(sparse_output=False)
cat_encoded = encoder.fit_transform(df[cat_features])

features = np.hstack([num_scaled, cat_encoded])

# === 3. Simpan scaler, encoder, features, dataset ===
pickle.dump(scaler, open("scaler.pkl", "wb"))
pickle.dump(encoder, open("encoder.pkl", "wb"))
np.save("features.npy", features)
df.to_pickle("df.pkl")

# === 4. Dummy target untuk MLP (pakai CBF similarity mean) ===
sim_scores = cosine_similarity(features, features).mean(axis=1)

X_train, X_test, y_train, y_test = train_test_split(features, sim_scores, test_size=0.2, random_state=42)

# === 5. MLP Model ===
input_dim = features.shape[1]
mlp_model = Sequential([
    Dense(64, input_dim=input_dim, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])
mlp_model.compile(optimizer='adam', loss='mse')

mlp_model.fit(X_train, y_train, epochs=50, batch_size=8, validation_data=(X_test, y_test), verbose=1)

# === 6. Evaluasi MLP ===
y_pred = mlp_model.predict(X_test).flatten()
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f"MLP Evaluation → MSE: {mse:.4f}, RMSE: {rmse:.4f}")

# === 7. Simpan model MLP (.keras native) ===
mlp_model.save("mlp_model.keras")
print("Pipeline selesai, semua model dan file disimpan!")

# === 8. Fungsi rekomendasi ===
def recommend(user_input, top_n=5, alpha=0.5, beta=0.5):
    """
    user_input: dict
        {'Province': 'Jawa Barat',
         'difficulty_level': 'Moderate',
         'hiking_duration_hours': 5}
    """
    # Load objects
    scaler = pickle.load(open("scaler.pkl","rb"))
    encoder = pickle.load(open("encoder.pkl","rb"))
    features = np.load("features.npy")
    df = pd.read_pickle("df.pkl")
    mlp_model = load_model("mlp_model.keras", compile=False)

    # Filter sesuai provinsi & difficulty
    filtered = df[(df['Province']==user_input['Province']) &
                  (df['difficulty_level']==user_input['difficulty_level'])].copy()

    if filtered.empty:
        return pd.DataFrame()

    idx_filtered = filtered.index

    # Buat vector user
    user_num = np.array([[0, user_input['hiking_duration_hours'], 0]])
    user_num_scaled = scaler.transform(user_num)

    user_cat = [[user_input['difficulty_level'], 'Intermediate', user_input['Province']]]
    user_cat_encoded = encoder.transform(user_cat)

    user_vector = np.hstack([user_num_scaled, user_cat_encoded])

    # CBF similarity
    sim_scores = cosine_similarity(user_vector, features[idx_filtered])[0]
    filtered['cbf_similarity'] = sim_scores

    # MLP scoring
    X_mlp = features[idx_filtered]
    mlp_scores = mlp_model.predict(X_mlp, verbose=0).flatten()

    # Gabungkan skor
    filtered['final_score'] = alpha*filtered['cbf_similarity'] + beta*mlp_scores
    return filtered.sort_values('final_score', ascending=False).head(top_n)